# Chapter 4.2: Universal Functions

A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

In [1]:
import numpy as np

In [5]:
# Make a sequence of 10 numbers from 0-9 and put in a 1x10 array
arr = np.arange(10)

In [6]:
# Take the square root of each element in an array arr
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
# Take exp of each element in an array arr
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
x = np.random.randn(8) #Put 8 random numbers in an 8 element array and call it "x"

In [12]:
y = np.random.randn(8) #Put 8 random numbers in an 8 element array and call it "y"

In [13]:
np.maximum(x,y) #Given x and y, what is each max element in the 8 slots?

array([ 0.67108188,  0.2441841 , -0.59343671, -1.49010584,  2.09457885,
       -0.88328892,  1.13506584, -0.58814838])

While not common, a ufunc can return multiple arrays. modf is one example, a vectorized version of the built-in Python divmod; it returns the fractional and integral parts of a floating-point array:

In [14]:
arr = np.random.randn(7)*5

In [15]:
arr

array([ 3.3293314 , 11.48346624, -0.71016363, -1.34288344, -3.13471571,
       -6.49230556, -2.15237847])

In [16]:
remainder, whole_part = np.modf(arr)

In [17]:
remainder

array([ 0.3293314 ,  0.48346624, -0.71016363, -0.34288344, -0.13471571,
       -0.49230556, -0.15237847])

In [18]:
whole_part

array([ 3., 11., -0., -1., -3., -6., -2.])